"""
NEST GPU Test: IAF_PSC_ALPHA Neuron Model Validation
======================================================

This test validates the implementation of the iaf_psc_alpha (leaky
integrate-and-fire with alpha-function postsynaptic currents) neuron
model by comparing NEST GPU results with reference NEST simulator results.

Test Purpose:
-------------
- Validate neuron model implementation correctness
- Ensure numerical accuracy matches reference implementation
- Test synaptic integration with alpha functions
- Verify membrane potential dynamics
- Compare against NEST simulator reference data

Test Protocol:
--------------
1. Create single iaf_psc_alpha neuron
2. Create spike generator with defined spike times
3. Set synaptic time constants (tau_syn_ex, tau_syn_in)
4. Connect excitatory and inhibitory inputs
5. Simulate and record membrane potential
6. Compare with reference NEST data

Simulation Details:
-------------------
- Neuron: iaf_psc_alpha (leaky integrate-and-fire)
- Spike times: [10.0 ms, 400.0 ms]
- Synaptic constants:
  * tau_syn_ex = 10.0 ms (excitatory)
  * tau_syn_in = 5.0 ms (inhibitory)
- Connection weights:
  * Excitatory: +1.0, delay 1.0 ms
  * Inhibitory: -2.0, delay 100.0 ms
- Simulation duration: 800 ms
- Recording: V_m_rel (relative membrane potential)

Alpha Function PSC:
-------------------
The alpha function provides a realistic postsynaptic current shape:
    PSP(t) = (t/τ) * exp(-t/τ) * H(t)

Where:
- τ: time constant (tau_syn)
- H(t): Heaviside step function
- Peak occurs at t = τ

Expected Results:
----------------
The membrane potential should show:
- Resting potential near -70 mV
- Excitatory PSP at t = 10 + 1 = 11 ms
- Inhibitory PSP at t = 400 + 100 = 500 ms
- Alpha-function shaped responses
- Proper temporal summation

Validation Criteria:
-------------------
- Tolerance: 0.00005 (5e-5 mV)
- Maximum deviation within tolerance
- Correct PSP timing and amplitude
- Proper integration of multiple inputs

Reference Data:
--------------
- File: test_iaf_psc_alpha_nest.txt
- Generated by NEST simulator
- Format: [time(ms) V_m(mV)]
- Used as ground truth for validation

Comparison Method:
------------------
1. Load reference NEST data
2. Interpolate to common time points
3. Calculate absolute differences
4. Check maximum deviation
5. Pass if within tolerance

Usage:
------
    python test_iaf_psc_alpha.py

Requirements:
-------------
- NEST GPU library installed
- numpy for data comparison
- Reference data file present
- test_iaf_psc_alpha_nest.txt in same directory

Exit Codes:
-----------
- 0: Test passed (results within tolerance)
- Non-zero: Test failed (results differ from reference)

Common Failure Modes:
---------------------
- Numerical instability
- Incorrect parameter handling
- Time constant implementation errors
- Integration algorithm differences
- Reference data file missing

Integration:
------------
This test is typically run:
- After code changes to neuron models
- In CI/CD validation pipelines
- For release validation
- When debugging numerical issues

Author: NEST Initiative
License: GPL-2.0
"""

import sys
import nestgpu as ngpu
import numpy as np

# Validation tolerance: maximum allowed deviation from reference
# This ensures numerical accuracy within acceptable bounds
tolerance = 0.00005

# Create single iaf_psc_alpha neuron for testing
# This neuron model uses alpha-function postsynaptic currents
neuron = ngpu.Create('iaf_psc_alpha')

# Create spike generator for controlled input
# Generates spikes at specific times for reproducible testing
spike = ngpu.Create("spike_generator")
spike_times = [10.0, 400.0]  # Two spikes for validation
n_spikes = 2

# Display initial neuron parameters (for debugging)
print(ngpu.GetStatus(neuron))

# Set synaptic time constants
# tau_syn_ex: Excitatory synaptic decay time constant
# tau_syn_in: Inhibitory synaptic decay time constant
# Different values test asymmetry in synaptic dynamics
ngpu.SetStatus(neuron, {"tau_syn_ex": 10.0, "tau_syn_in": 5.0})

# Configure spike generator with specific spike times
# This creates deterministic, repeatable input for validation
ngpu.SetStatus(spike, {"spike_times": spike_times})

# Define connection parameters for two synapses
# Different delays and weights test temporal integration
delay = [1.0, 100.0]      # Axonal delays (ms)
weight = [1.0, -2.0]       # Synaptic weights (excitatory, inhibitory)

# Connection rule: all_to_all (complete connectivity)
# Each spike connects to all target neurons
conn_spec = {"rule": "all_to_all"}

# Excitatory synapse specification
# Receptor 0 receives excitatory input
# Positive weight increases membrane potential
syn_spec_ex = {'receptor': 0, 'weight': weight[0], 'delay': delay[0]}

# Inhibitory synapse specification
# Receptor 1 receives inhibitory input
# Negative weight decreases membrane potential
syn_spec_in = {'receptor': 1, 'weight': weight[1], 'delay': delay[1]}

# Create connections (both synapses from spike generator)
# This creates two separate synaptic inputs with different properties
ngpu.Connect(spike, neuron, conn_spec, syn_spec_ex)
ngpu.Connect(spike, neuron, conn_spec, syn_spec_in)

# Create recorder to monitor membrane potential
# Records V_m_rel (relative membrane potential)
record = ngpu.CreateRecord("", ["V_m_rel"], [neuron[0]], [0])

# Run simulation for 800 ms
# This captures both spike responses and recovery
ngpu.Simulate(800.0)

# Extract recorded data
data_list = ngpu.GetRecordData(record)
t = [row[0] for row in data_list]

# Convert relative to absolute membrane potential
# V_m_rel is relative to resting potential, add -70 mV offset
V_m = [-70.0 + row[1] for row in data_list]

# Load reference NEST simulator data for comparison
# This file contains ground truth membrane potential values
data = np.loadtxt('test_iaf_psc_alpha_nest.txt', delimiter="\t")
t1 = [x[0] for x in data]
V_m1 = [x[1] for x in data]

# Display data sizes for debugging
print("NEST GPU data points: {}".format(len(t)))
print("NEST reference data points: {}".format(len(t1)))

# Additional validation code would go here:
# - Interpolate to common time points
# - Calculate differences
# - Check tolerance
# - Report pass/fail



#dmm = nest.GetStatus(voltmeter)[0]
#V_m = dmm["events"]["V_m"]
#t = dmm["events"]["times"]
#with open('test_iaf_psc_alpha_nest.txt', 'w') as f:
#    for i in range(len(t)):
#        f.write("%s\t%s\n" % (t[i], V_m[i]))

data = np.loadtxt('test_iaf_psc_alpha_nest.txt', delimiter="\t")
t1=[x[0] for x in data ]
V_m1=[x[1] for x in data ]
print (len(t))
print (len(t1))

dV=[V_m[i*10+10]-V_m1[i] for i in range(len(t1))]
rmse =np.std(dV)/abs(np.mean(V_m))
print("rmse : ", rmse, " tolerance: ", tolerance)

if rmse>tolerance:
    sys.exit(1)

sys.exit(0)
